#!/bin/sh
HOST_DIR=$1
FILE_NAME=$2
TEST_CASE=$3
TARGET_DIR="/home/root/unit-test"
TARGET_GCOV_PREFIX="${TARGET_DIR}/output"
TARGET_USER="root"
TARGET_ADDRESS="zedboard.windhoverlabs.lan"

ssh ${TARGET_USER}@${TARGET_ADDRESS} "mkdir -p ${TARGET_DIR}"
scp -r ${HOST_DIR}/${FILE_NAME} ${TARGET_USER}@${TARGET_ADDRESS}:${TARGET_DIR}
ssh ${TARGET_USER}@${TARGET_ADDRESS} "GCOV_PREFIX=${TARGET_GCOV_PREFIX} GCOV_PREFIX_STRIP=0 ${TARGET_DIR}/${FILE_NAME} --test ${TEST_CASE} --report_level=no --log_level=all --output_format=xml --log_sink=/home/root/unit-test/output/var/jenkins/workspace/Airliner_OcPoC/build/ocpoc/default/target/test_logs/${FILE_NAME}.xml"
RETURN_CODE=$?
scp -r ${TARGET_USER}@${TARGET_ADDRESS}:${TARGET_GCOV_PREFIX}/* /
#ssh ${TARGET_USER}@${TARGET_ADDRESS} "rm -Rf ${TARGET_DIR}"

exit ${RETURN_CODE}
