# TODO Put into Geographic
ACTION_CALC_PBD = 'ACTION_CALC_PBD'
ACTION_CALC_BEARING = 'ACTION_CALC_BEARING'
ACTION_CALC_DISTANCE = 'ACTION_CALC_DISTANCE'

# TODO Put into Controller
ACTION_ARM = 'ACTION_ARM'
ACTION_DISARM = 'ACTION_DISARM'
ACTION_RTL = 'ACTION_RTL'
ACTION_TAKEOFF = 'ACTION_TAKEOFF'

# TODO Put into Communication
ACTION_SEND_COMMAND = 'ACTION_SEND_COMMAND'
ACTION_SEND_BYTES = 'ACTION_SEND_BYTES'

ACTION_CONTROL_GRANT = 'ACTION_CONTROL_GRANT'
ACTION_CONTROL_REQUEST = 'ACTION_CONTROL_REQUEST'
ACTION_CONTROL_RELEASE = 'ACTION_CONTROL_RELEASE'
ACTION_CONTROL_REVOKE = 'ACTION_CONTROL_REVOKE'

ACTION_TELEM = 'ACTION_TELEM'

# TODO Put into BaseVehicle
ACTION_COMPONENT_ATTACH = 'ACTION_COMPONENT_ATTACH'
ACTION_COMPONENT_DETACH = 'ACTION_COMPONENT_DETACH'
ACTION_COMPONENT_LIST = 'ACTION_COMPONENT_LIST'
# ACTION_COMPONENT_START = 'ACTION_COMPONENT_START'
# ACTION_COMPONENT_STOP = 'ACTION_COMPONENT_STOP'

# TODO Put into FlightDirector
ACTION_AXIS_SET = 'ACTION_AXIS_SET'
ACTION_AXIS_ZERO = 'ACTION_AXIS_ZERO'
