# TODO Put into geographic
ACTION_CALC_PBD = 'ACTION_CALC_PBD'
ACTION_CALC_BEARING = 'ACTION_CALC_BEARING'
ACTION_CALC_DISTANCE = 'ACTION_CALC_DISTANCE'

# TODO Put into controller
ACTION_ARM = 'ACTION_ARM'
ACTION_DISARM = 'ACTION_DISARM'
ACTION_RTL = 'ACTION_RTL'
ACTION_TAKEOFF = 'ACTION_TAKEOFF'

# TODO Put into BaseVehicle
ACTION_COMPONENT_ATTACH = 'ACTION_COMPONENT_ATTACH'
ACTION_COMPONENT_DETACH = 'ACTION_COMPONENT_DETACH'
ACTION_COMPONENT_START = 'ACTION_COMPONENT_START'
ACTION_COMPONENT_STOP = 'ACTION_COMPONENT_STOP'

ACTION_CONTROL_GRANT = 'ACTION_CONTROL_GRANT'
ACTION_CONTROL_REVOKE = 'ACTION_CONTROL_REVOKE'

ACTION_COMPONENT_LIST = 'ACTION_COMPONENT_LIST'

# TODO Put into FlightDirector
ACTION_AXIS_SET = 'ACTION_SET_AXIS'
ACTION_AXIS_ZERO = 'ACTION_AXIS_ZERO'
