#!/bin/bash

SERIAL_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
INPUT_FILE=$1
OUTPUT_DIR=$2

cp $INPUT_FILE $SERIAL_DIR
cd $SERIAL_DIR/
python autogen.py
echo cp -R $SERIAL_DIR/src/ $OUTPUT_DIR
cp -R $SERIAL_DIR/src/ $OUTPUT_DIR
