#!/bin/bash

SERIAL_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
SERIALIZATION_FILE=$1
OPS_FILE=$2
MSGS_FILE=$3
OUTPUT_FILE=$4

cd $SERIAL_DIR/
echo python merge.py --pyliner-json $SERIALIZATION_FILE --ops $OPS_FILE --msgs $MSGS_FILE
python merge.py --pyliner-json $SERIALIZATION_FILE --ops $OPS_FILE --msgs $MSGS_FILE
mv merged.json ${OUTPUT_FILE}
