# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: _py_CFE_ES_ERLog_t.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='_py_CFE_ES_ERLog_t.proto',
  package='',
  serialized_pb=_b('\n\x18_py_CFE_ES_ERLog_t.proto\"<\n\x15\x43\x46\x45_TIME_SysTime_t_pb\x12\x0f\n\x07Seconds\x18\x01 \x02(\r\x12\x12\n\nSubseconds\x18\x02 \x02(\r\"x\n\x1a\x43\x46\x45_ES_DebugVariables_t_pb\x12\x19\n\x11WatchdogWriteFlag\x18\x01 \x02(\r\x12\x11\n\tDebugFlag\x18\x02 \x02(\r\x12\x11\n\tLastAppId\x18\x03 \x02(\r\x12\x19\n\x11PrintfEnabledFlag\x18\x04 \x02(\r\"\xc7\x02\n\x11\x43\x46\x45_ES_ERLog_t_pb\x12\x14\n\x0cResetSubtype\x18\x01 \x02(\r\x12.\n\tDebugVars\x18\x02 \x02(\x0b\x32\x1b.CFE_ES_DebugVariables_t_pb\x12\x1b\n\x13ProcessorResetCount\x18\x03 \x02(\r\x12\x13\n\x0b\x43ontextSize\x18\x04 \x02(\r\x12\x14\n\x0cLogEntryType\x18\x05 \x02(\r\x12\x11\n\tResetType\x18\x06 \x02(\r\x12\x0f\n\x07\x43ontext\x18\x07 \x03(\r\x12\r\n\x05\x41ppID\x18\x08 \x02(\r\x12(\n\x08TimeCode\x18\t \x02(\x0b\x32\x16.CFE_TIME_SysTime_t_pb\x12\x13\n\x0b\x44\x65scription\x18\n \x02(\t\x12\x1e\n\x16MaxProcessorResetCount\x18\x0b \x02(\r\x12\x12\n\nBootSource\x18\x0c \x02(\r')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CFE_TIME_SYSTIME_T_PB = _descriptor.Descriptor(
  name='CFE_TIME_SysTime_t_pb',
  full_name='CFE_TIME_SysTime_t_pb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Seconds', full_name='CFE_TIME_SysTime_t_pb.Seconds', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Subseconds', full_name='CFE_TIME_SysTime_t_pb.Subseconds', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=88,
)


_CFE_ES_DEBUGVARIABLES_T_PB = _descriptor.Descriptor(
  name='CFE_ES_DebugVariables_t_pb',
  full_name='CFE_ES_DebugVariables_t_pb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='WatchdogWriteFlag', full_name='CFE_ES_DebugVariables_t_pb.WatchdogWriteFlag', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DebugFlag', full_name='CFE_ES_DebugVariables_t_pb.DebugFlag', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='LastAppId', full_name='CFE_ES_DebugVariables_t_pb.LastAppId', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PrintfEnabledFlag', full_name='CFE_ES_DebugVariables_t_pb.PrintfEnabledFlag', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=210,
)


_CFE_ES_ERLOG_T_PB = _descriptor.Descriptor(
  name='CFE_ES_ERLog_t_pb',
  full_name='CFE_ES_ERLog_t_pb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ResetSubtype', full_name='CFE_ES_ERLog_t_pb.ResetSubtype', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DebugVars', full_name='CFE_ES_ERLog_t_pb.DebugVars', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ProcessorResetCount', full_name='CFE_ES_ERLog_t_pb.ProcessorResetCount', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ContextSize', full_name='CFE_ES_ERLog_t_pb.ContextSize', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='LogEntryType', full_name='CFE_ES_ERLog_t_pb.LogEntryType', index=4,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ResetType', full_name='CFE_ES_ERLog_t_pb.ResetType', index=5,
      number=6, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Context', full_name='CFE_ES_ERLog_t_pb.Context', index=6,
      number=7, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='AppID', full_name='CFE_ES_ERLog_t_pb.AppID', index=7,
      number=8, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='TimeCode', full_name='CFE_ES_ERLog_t_pb.TimeCode', index=8,
      number=9, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Description', full_name='CFE_ES_ERLog_t_pb.Description', index=9,
      number=10, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='MaxProcessorResetCount', full_name='CFE_ES_ERLog_t_pb.MaxProcessorResetCount', index=10,
      number=11, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='BootSource', full_name='CFE_ES_ERLog_t_pb.BootSource', index=11,
      number=12, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=540,
)

_CFE_ES_ERLOG_T_PB.fields_by_name['DebugVars'].message_type = _CFE_ES_DEBUGVARIABLES_T_PB
_CFE_ES_ERLOG_T_PB.fields_by_name['TimeCode'].message_type = _CFE_TIME_SYSTIME_T_PB
DESCRIPTOR.message_types_by_name['CFE_TIME_SysTime_t_pb'] = _CFE_TIME_SYSTIME_T_PB
DESCRIPTOR.message_types_by_name['CFE_ES_DebugVariables_t_pb'] = _CFE_ES_DEBUGVARIABLES_T_PB
DESCRIPTOR.message_types_by_name['CFE_ES_ERLog_t_pb'] = _CFE_ES_ERLOG_T_PB

CFE_TIME_SysTime_t_pb = _reflection.GeneratedProtocolMessageType('CFE_TIME_SysTime_t_pb', (_message.Message,), dict(
  DESCRIPTOR = _CFE_TIME_SYSTIME_T_PB,
  __module__ = '_py_CFE_ES_ERLog_t_pb2'
  # @@protoc_insertion_point(class_scope:CFE_TIME_SysTime_t_pb)
  ))
_sym_db.RegisterMessage(CFE_TIME_SysTime_t_pb)

CFE_ES_DebugVariables_t_pb = _reflection.GeneratedProtocolMessageType('CFE_ES_DebugVariables_t_pb', (_message.Message,), dict(
  DESCRIPTOR = _CFE_ES_DEBUGVARIABLES_T_PB,
  __module__ = '_py_CFE_ES_ERLog_t_pb2'
  # @@protoc_insertion_point(class_scope:CFE_ES_DebugVariables_t_pb)
  ))
_sym_db.RegisterMessage(CFE_ES_DebugVariables_t_pb)

CFE_ES_ERLog_t_pb = _reflection.GeneratedProtocolMessageType('CFE_ES_ERLog_t_pb', (_message.Message,), dict(
  DESCRIPTOR = _CFE_ES_ERLOG_T_PB,
  __module__ = '_py_CFE_ES_ERLog_t_pb2'
  # @@protoc_insertion_point(class_scope:CFE_ES_ERLog_t_pb)
  ))
_sym_db.RegisterMessage(CFE_ES_ERLog_t_pb)


# @@protoc_insertion_point(module_scope)
