# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: _py_CFE_TBL_LoadBuff_t.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='_py_CFE_TBL_LoadBuff_t.proto',
  package='',
  serialized_pb=_b('\n\x1c_py_CFE_TBL_LoadBuff_t.proto\"\xa8\x01\n\x15\x43\x46\x45_TBL_LoadBuff_t_pb\x12\x1a\n\x12\x46ileCreateTimeSecs\x18\x01 \x02(\r\x12\x1d\n\x15\x46ileCreateTimeSubSecs\x18\x02 \x02(\r\x12\x0b\n\x03\x43rc\x18\x03 \x02(\r\x12\x11\n\tBufferPtr\x18\x04 \x02(\r\x12\r\n\x05Taken\x18\x05 \x02(\x08\x12\x11\n\tValidated\x18\x06 \x02(\x08\x12\x12\n\nDataSource\x18\x07 \x02(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CFE_TBL_LOADBUFF_T_PB = _descriptor.Descriptor(
  name='CFE_TBL_LoadBuff_t_pb',
  full_name='CFE_TBL_LoadBuff_t_pb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='FileCreateTimeSecs', full_name='CFE_TBL_LoadBuff_t_pb.FileCreateTimeSecs', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='FileCreateTimeSubSecs', full_name='CFE_TBL_LoadBuff_t_pb.FileCreateTimeSubSecs', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Crc', full_name='CFE_TBL_LoadBuff_t_pb.Crc', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='BufferPtr', full_name='CFE_TBL_LoadBuff_t_pb.BufferPtr', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Taken', full_name='CFE_TBL_LoadBuff_t_pb.Taken', index=4,
      number=5, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Validated', full_name='CFE_TBL_LoadBuff_t_pb.Validated', index=5,
      number=6, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DataSource', full_name='CFE_TBL_LoadBuff_t_pb.DataSource', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=201,
)

DESCRIPTOR.message_types_by_name['CFE_TBL_LoadBuff_t_pb'] = _CFE_TBL_LOADBUFF_T_PB

CFE_TBL_LoadBuff_t_pb = _reflection.GeneratedProtocolMessageType('CFE_TBL_LoadBuff_t_pb', (_message.Message,), dict(
  DESCRIPTOR = _CFE_TBL_LOADBUFF_T_PB,
  __module__ = '_py_CFE_TBL_LoadBuff_t_pb2'
  # @@protoc_insertion_point(class_scope:CFE_TBL_LoadBuff_t_pb)
  ))
_sym_db.RegisterMessage(CFE_TBL_LoadBuff_t_pb)


# @@protoc_insertion_point(module_scope)
