# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: _py_CFE_SB_HKMsg_t.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='_py_CFE_SB_HKMsg_t.proto',
  package='',
  serialized_pb=_b('\n\x18_py_CFE_SB_HKMsg_t.proto\"\x89\x03\n\x19\x43\x46\x45_SB_HKMsg_Payload_t_pb\x12\x13\n\x0bUnmarkedMem\x18\x01 \x02(\r\x12\x13\n\x0bSpare2Align\x18\x02 \x03(\r\x12\x18\n\x10MsgReceiveErrCnt\x18\x03 \x02(\r\x12\x11\n\tCmdErrCnt\x18\x04 \x02(\r\x12\x18\n\x10NoSubscribersCnt\x18\x05 \x02(\r\x12\x1a\n\x12PipeOverflowErrCnt\x18\x06 \x02(\r\x12\x14\n\x0cMsgLimErrCnt\x18\x07 \x02(\r\x12\x18\n\x10\x43reatePipeErrCnt\x18\x08 \x02(\r\x12\r\n\x05Spare\x18\t \x02(\r\x12\x15\n\rMemPoolHandle\x18\n \x02(\r\x12\x16\n\x0eInternalErrCnt\x18\x0b \x02(\r\x12\x15\n\rMsgSendErrCnt\x18\x0c \x02(\r\x12\x10\n\x08MemInUse\x18\r \x02(\r\x12\x1b\n\x13\x44upSubscriptionsCnt\x18\x0e \x02(\r\x12\x17\n\x0fSubscribeErrCnt\x18\x0f \x02(\r\x12\x12\n\nCommandCnt\x18\x10 \x02(\r\"Y\n\x12\x43\x46\x45_SB_TlmHdr_t_pb\x12\x1f\n\x03Pri\x18\x01 \x02(\x0b\x32\x12.CCSDS_PriHdr_t_pb\x12\"\n\x03Sec\x18\x02 \x02(\x0b\x32\x15.CCSDS_TlmSecHdr_t_pb\"$\n\x14\x43\x43SDS_TlmSecHdr_t_pb\x12\x0c\n\x04Time\x18\x01 \x03(\r\"G\n\x11\x43\x43SDS_PriHdr_t_pb\x12\x0e\n\x06Length\x18\x01 \x03(\r\x12\x10\n\x08Sequence\x18\x02 \x03(\r\x12\x10\n\x08StreamId\x18\x03 \x03(\r\"b\n\x11\x43\x46\x45_SB_HKMsg_t_pb\x12 \n\x03Hdr\x18\x01 \x02(\x0b\x32\x13.CFE_SB_TlmHdr_t_pb\x12+\n\x07Payload\x18\x02 \x02(\x0b\x32\x1a.CFE_SB_HKMsg_Payload_t_pb')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CFE_SB_HKMSG_PAYLOAD_T_PB = _descriptor.Descriptor(
  name='CFE_SB_HKMsg_Payload_t_pb',
  full_name='CFE_SB_HKMsg_Payload_t_pb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='UnmarkedMem', full_name='CFE_SB_HKMsg_Payload_t_pb.UnmarkedMem', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Spare2Align', full_name='CFE_SB_HKMsg_Payload_t_pb.Spare2Align', index=1,
      number=2, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='MsgReceiveErrCnt', full_name='CFE_SB_HKMsg_Payload_t_pb.MsgReceiveErrCnt', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='CmdErrCnt', full_name='CFE_SB_HKMsg_Payload_t_pb.CmdErrCnt', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='NoSubscribersCnt', full_name='CFE_SB_HKMsg_Payload_t_pb.NoSubscribersCnt', index=4,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PipeOverflowErrCnt', full_name='CFE_SB_HKMsg_Payload_t_pb.PipeOverflowErrCnt', index=5,
      number=6, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='MsgLimErrCnt', full_name='CFE_SB_HKMsg_Payload_t_pb.MsgLimErrCnt', index=6,
      number=7, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='CreatePipeErrCnt', full_name='CFE_SB_HKMsg_Payload_t_pb.CreatePipeErrCnt', index=7,
      number=8, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Spare', full_name='CFE_SB_HKMsg_Payload_t_pb.Spare', index=8,
      number=9, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='MemPoolHandle', full_name='CFE_SB_HKMsg_Payload_t_pb.MemPoolHandle', index=9,
      number=10, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='InternalErrCnt', full_name='CFE_SB_HKMsg_Payload_t_pb.InternalErrCnt', index=10,
      number=11, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='MsgSendErrCnt', full_name='CFE_SB_HKMsg_Payload_t_pb.MsgSendErrCnt', index=11,
      number=12, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='MemInUse', full_name='CFE_SB_HKMsg_Payload_t_pb.MemInUse', index=12,
      number=13, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DupSubscriptionsCnt', full_name='CFE_SB_HKMsg_Payload_t_pb.DupSubscriptionsCnt', index=13,
      number=14, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SubscribeErrCnt', full_name='CFE_SB_HKMsg_Payload_t_pb.SubscribeErrCnt', index=14,
      number=15, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='CommandCnt', full_name='CFE_SB_HKMsg_Payload_t_pb.CommandCnt', index=15,
      number=16, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=422,
)


_CFE_SB_TLMHDR_T_PB = _descriptor.Descriptor(
  name='CFE_SB_TlmHdr_t_pb',
  full_name='CFE_SB_TlmHdr_t_pb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Pri', full_name='CFE_SB_TlmHdr_t_pb.Pri', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Sec', full_name='CFE_SB_TlmHdr_t_pb.Sec', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=424,
  serialized_end=513,
)


_CCSDS_TLMSECHDR_T_PB = _descriptor.Descriptor(
  name='CCSDS_TlmSecHdr_t_pb',
  full_name='CCSDS_TlmSecHdr_t_pb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Time', full_name='CCSDS_TlmSecHdr_t_pb.Time', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=515,
  serialized_end=551,
)


_CCSDS_PRIHDR_T_PB = _descriptor.Descriptor(
  name='CCSDS_PriHdr_t_pb',
  full_name='CCSDS_PriHdr_t_pb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Length', full_name='CCSDS_PriHdr_t_pb.Length', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Sequence', full_name='CCSDS_PriHdr_t_pb.Sequence', index=1,
      number=2, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='StreamId', full_name='CCSDS_PriHdr_t_pb.StreamId', index=2,
      number=3, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=553,
  serialized_end=624,
)


_CFE_SB_HKMSG_T_PB = _descriptor.Descriptor(
  name='CFE_SB_HKMsg_t_pb',
  full_name='CFE_SB_HKMsg_t_pb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Hdr', full_name='CFE_SB_HKMsg_t_pb.Hdr', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Payload', full_name='CFE_SB_HKMsg_t_pb.Payload', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=626,
  serialized_end=724,
)

_CFE_SB_TLMHDR_T_PB.fields_by_name['Pri'].message_type = _CCSDS_PRIHDR_T_PB
_CFE_SB_TLMHDR_T_PB.fields_by_name['Sec'].message_type = _CCSDS_TLMSECHDR_T_PB
_CFE_SB_HKMSG_T_PB.fields_by_name['Hdr'].message_type = _CFE_SB_TLMHDR_T_PB
_CFE_SB_HKMSG_T_PB.fields_by_name['Payload'].message_type = _CFE_SB_HKMSG_PAYLOAD_T_PB
DESCRIPTOR.message_types_by_name['CFE_SB_HKMsg_Payload_t_pb'] = _CFE_SB_HKMSG_PAYLOAD_T_PB
DESCRIPTOR.message_types_by_name['CFE_SB_TlmHdr_t_pb'] = _CFE_SB_TLMHDR_T_PB
DESCRIPTOR.message_types_by_name['CCSDS_TlmSecHdr_t_pb'] = _CCSDS_TLMSECHDR_T_PB
DESCRIPTOR.message_types_by_name['CCSDS_PriHdr_t_pb'] = _CCSDS_PRIHDR_T_PB
DESCRIPTOR.message_types_by_name['CFE_SB_HKMsg_t_pb'] = _CFE_SB_HKMSG_T_PB

CFE_SB_HKMsg_Payload_t_pb = _reflection.GeneratedProtocolMessageType('CFE_SB_HKMsg_Payload_t_pb', (_message.Message,), dict(
  DESCRIPTOR = _CFE_SB_HKMSG_PAYLOAD_T_PB,
  __module__ = '_py_CFE_SB_HKMsg_t_pb2'
  # @@protoc_insertion_point(class_scope:CFE_SB_HKMsg_Payload_t_pb)
  ))
_sym_db.RegisterMessage(CFE_SB_HKMsg_Payload_t_pb)

CFE_SB_TlmHdr_t_pb = _reflection.GeneratedProtocolMessageType('CFE_SB_TlmHdr_t_pb', (_message.Message,), dict(
  DESCRIPTOR = _CFE_SB_TLMHDR_T_PB,
  __module__ = '_py_CFE_SB_HKMsg_t_pb2'
  # @@protoc_insertion_point(class_scope:CFE_SB_TlmHdr_t_pb)
  ))
_sym_db.RegisterMessage(CFE_SB_TlmHdr_t_pb)

CCSDS_TlmSecHdr_t_pb = _reflection.GeneratedProtocolMessageType('CCSDS_TlmSecHdr_t_pb', (_message.Message,), dict(
  DESCRIPTOR = _CCSDS_TLMSECHDR_T_PB,
  __module__ = '_py_CFE_SB_HKMsg_t_pb2'
  # @@protoc_insertion_point(class_scope:CCSDS_TlmSecHdr_t_pb)
  ))
_sym_db.RegisterMessage(CCSDS_TlmSecHdr_t_pb)

CCSDS_PriHdr_t_pb = _reflection.GeneratedProtocolMessageType('CCSDS_PriHdr_t_pb', (_message.Message,), dict(
  DESCRIPTOR = _CCSDS_PRIHDR_T_PB,
  __module__ = '_py_CFE_SB_HKMsg_t_pb2'
  # @@protoc_insertion_point(class_scope:CCSDS_PriHdr_t_pb)
  ))
_sym_db.RegisterMessage(CCSDS_PriHdr_t_pb)

CFE_SB_HKMsg_t_pb = _reflection.GeneratedProtocolMessageType('CFE_SB_HKMsg_t_pb', (_message.Message,), dict(
  DESCRIPTOR = _CFE_SB_HKMSG_T_PB,
  __module__ = '_py_CFE_SB_HKMsg_t_pb2'
  # @@protoc_insertion_point(class_scope:CFE_SB_HKMsg_t_pb)
  ))
_sym_db.RegisterMessage(CFE_SB_HKMsg_t_pb)


# @@protoc_insertion_point(module_scope)
