# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: _py_CFE_SB_PipeD_t.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='_py_CFE_SB_PipeD_t.proto',
  package='',
  serialized_pb=_b('\n\x18_py_CFE_SB_PipeD_t.proto\"\xed\x01\n\x11\x43\x46\x45_SB_PipeD_t_pb\x12\x12\n\nSendErrors\x18\x01 \x02(\r\x12\r\n\x05InUse\x18\x02 \x02(\r\x12\x12\n\nLastSender\x18\x03 \x02(\r\x12\x0f\n\x07\x41ppName\x18\x04 \x02(\t\x12\x12\n\nQueueDepth\x18\x05 \x02(\r\x12\x13\n\x0bToTrashBuff\x18\x06 \x02(\r\x12\r\n\x05Spare\x18\x07 \x02(\r\x12\x10\n\x08PipeName\x18\x08 \x02(\t\x12\r\n\x05\x41ppId\x18\t \x02(\r\x12\x12\n\nSysQueueId\x18\n \x02(\r\x12\x0e\n\x06PipeId\x18\x0b \x02(\t\x12\x13\n\x0b\x43urrentBuff\x18\x0c \x02(\r')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CFE_SB_PIPED_T_PB = _descriptor.Descriptor(
  name='CFE_SB_PipeD_t_pb',
  full_name='CFE_SB_PipeD_t_pb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='SendErrors', full_name='CFE_SB_PipeD_t_pb.SendErrors', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='InUse', full_name='CFE_SB_PipeD_t_pb.InUse', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='LastSender', full_name='CFE_SB_PipeD_t_pb.LastSender', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='AppName', full_name='CFE_SB_PipeD_t_pb.AppName', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='QueueDepth', full_name='CFE_SB_PipeD_t_pb.QueueDepth', index=4,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ToTrashBuff', full_name='CFE_SB_PipeD_t_pb.ToTrashBuff', index=5,
      number=6, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Spare', full_name='CFE_SB_PipeD_t_pb.Spare', index=6,
      number=7, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PipeName', full_name='CFE_SB_PipeD_t_pb.PipeName', index=7,
      number=8, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='AppId', full_name='CFE_SB_PipeD_t_pb.AppId', index=8,
      number=9, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SysQueueId', full_name='CFE_SB_PipeD_t_pb.SysQueueId', index=9,
      number=10, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PipeId', full_name='CFE_SB_PipeD_t_pb.PipeId', index=10,
      number=11, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='CurrentBuff', full_name='CFE_SB_PipeD_t_pb.CurrentBuff', index=11,
      number=12, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=266,
)

DESCRIPTOR.message_types_by_name['CFE_SB_PipeD_t_pb'] = _CFE_SB_PIPED_T_PB

CFE_SB_PipeD_t_pb = _reflection.GeneratedProtocolMessageType('CFE_SB_PipeD_t_pb', (_message.Message,), dict(
  DESCRIPTOR = _CFE_SB_PIPED_T_PB,
  __module__ = '_py_CFE_SB_PipeD_t_pb2'
  # @@protoc_insertion_point(class_scope:CFE_SB_PipeD_t_pb)
  ))
_sym_db.RegisterMessage(CFE_SB_PipeD_t_pb)


# @@protoc_insertion_point(module_scope)
