# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: _py_CFE_SB_ZeroCopyD_t.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='_py_CFE_SB_ZeroCopyD_t.proto',
  package='',
  serialized_pb=_b('\n\x1c_py_CFE_SB_ZeroCopyD_t.proto\"\x1b\n\tBuffer_pb\x12\x0e\n\x06\x42uffer\x18\x01 \x02(\r\"\x84\x01\n\x15\x43\x46\x45_SB_ZeroCopyD_t_pb\x12\x1a\n\x06\x42uffer\x18\x01 \x02(\x0b\x32\n.Buffer_pb\x12\x0c\n\x04Size\x18\x02 \x02(\r\x12\x18\n\x04Prev\x18\x03 \x02(\x0b\x32\n.Buffer_pb\x12\r\n\x05\x41ppID\x18\x04 \x02(\r\x12\x18\n\x04Next\x18\x05 \x02(\x0b\x32\n.Buffer_pb')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_BUFFER_PB = _descriptor.Descriptor(
  name='Buffer_pb',
  full_name='Buffer_pb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Buffer', full_name='Buffer_pb.Buffer', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=59,
)


_CFE_SB_ZEROCOPYD_T_PB = _descriptor.Descriptor(
  name='CFE_SB_ZeroCopyD_t_pb',
  full_name='CFE_SB_ZeroCopyD_t_pb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Buffer', full_name='CFE_SB_ZeroCopyD_t_pb.Buffer', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Size', full_name='CFE_SB_ZeroCopyD_t_pb.Size', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Prev', full_name='CFE_SB_ZeroCopyD_t_pb.Prev', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='AppID', full_name='CFE_SB_ZeroCopyD_t_pb.AppID', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Next', full_name='CFE_SB_ZeroCopyD_t_pb.Next', index=4,
      number=5, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=194,
)

_CFE_SB_ZEROCOPYD_T_PB.fields_by_name['Buffer'].message_type = _BUFFER_PB
_CFE_SB_ZEROCOPYD_T_PB.fields_by_name['Prev'].message_type = _BUFFER_PB
_CFE_SB_ZEROCOPYD_T_PB.fields_by_name['Next'].message_type = _BUFFER_PB
DESCRIPTOR.message_types_by_name['Buffer_pb'] = _BUFFER_PB
DESCRIPTOR.message_types_by_name['CFE_SB_ZeroCopyD_t_pb'] = _CFE_SB_ZEROCOPYD_T_PB

Buffer_pb = _reflection.GeneratedProtocolMessageType('Buffer_pb', (_message.Message,), dict(
  DESCRIPTOR = _BUFFER_PB,
  __module__ = '_py_CFE_SB_ZeroCopyD_t_pb2'
  # @@protoc_insertion_point(class_scope:Buffer_pb)
  ))
_sym_db.RegisterMessage(Buffer_pb)

CFE_SB_ZeroCopyD_t_pb = _reflection.GeneratedProtocolMessageType('CFE_SB_ZeroCopyD_t_pb', (_message.Message,), dict(
  DESCRIPTOR = _CFE_SB_ZEROCOPYD_T_PB,
  __module__ = '_py_CFE_SB_ZeroCopyD_t_pb2'
  # @@protoc_insertion_point(class_scope:CFE_SB_ZeroCopyD_t_pb)
  ))
_sym_db.RegisterMessage(CFE_SB_ZeroCopyD_t_pb)


# @@protoc_insertion_point(module_scope)
