# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: _py_EA_CdsTbl_t.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='_py_EA_CdsTbl_t.proto',
  package='',
  serialized_pb=_b('\n\x15_py_EA_CdsTbl_t.proto\" \n\x0e\x45\x41_CdsTbl_t_pb\x12\x0e\n\x06iParam\x18\x01 \x02(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_EA_CDSTBL_T_PB = _descriptor.Descriptor(
  name='EA_CdsTbl_t_pb',
  full_name='EA_CdsTbl_t_pb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='iParam', full_name='EA_CdsTbl_t_pb.iParam', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=57,
)

DESCRIPTOR.message_types_by_name['EA_CdsTbl_t_pb'] = _EA_CDSTBL_T_PB

EA_CdsTbl_t_pb = _reflection.GeneratedProtocolMessageType('EA_CdsTbl_t_pb', (_message.Message,), dict(
  DESCRIPTOR = _EA_CDSTBL_T_PB,
  __module__ = '_py_EA_CdsTbl_t_pb2'
  # @@protoc_insertion_point(class_scope:EA_CdsTbl_t_pb)
  ))
_sym_db.RegisterMessage(EA_CdsTbl_t_pb)


# @@protoc_insertion_point(module_scope)
