# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: _py_FM_HousekeepingPkt_t.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='_py_FM_HousekeepingPkt_t.proto',
  package='',
  serialized_pb=_b('\n\x1e_py_FM_HousekeepingPkt_t.proto\"\xa0\x02\n\x17\x46M_HousekeepingPkt_t_pb\x12\x1b\n\x13\x43hildCmdWarnCounter\x18\x01 \x02(\r\x12\x16\n\x0e\x43ommandCounter\x18\x02 \x02(\r\x12\x16\n\x0e\x43hildCurrentCC\x18\x03 \x02(\r\x12\x19\n\x11\x43ommandErrCounter\x18\x04 \x02(\r\x12\x14\n\x0cNumOpenFiles\x18\x05 \x02(\r\x12\x11\n\tTlmHeader\x18\x06 \x03(\r\x12\r\n\x05Spare\x18\x07 \x02(\r\x12\x17\n\x0f\x43hildQueueCount\x18\x08 \x02(\r\x12\x17\n\x0f\x43hildPreviousCC\x18\t \x02(\r\x12\x17\n\x0f\x43hildCmdCounter\x18\n \x02(\r\x12\x1a\n\x12\x43hildCmdErrCounter\x18\x0b \x02(\r')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_FM_HOUSEKEEPINGPKT_T_PB = _descriptor.Descriptor(
  name='FM_HousekeepingPkt_t_pb',
  full_name='FM_HousekeepingPkt_t_pb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ChildCmdWarnCounter', full_name='FM_HousekeepingPkt_t_pb.ChildCmdWarnCounter', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='CommandCounter', full_name='FM_HousekeepingPkt_t_pb.CommandCounter', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ChildCurrentCC', full_name='FM_HousekeepingPkt_t_pb.ChildCurrentCC', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='CommandErrCounter', full_name='FM_HousekeepingPkt_t_pb.CommandErrCounter', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='NumOpenFiles', full_name='FM_HousekeepingPkt_t_pb.NumOpenFiles', index=4,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='TlmHeader', full_name='FM_HousekeepingPkt_t_pb.TlmHeader', index=5,
      number=6, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Spare', full_name='FM_HousekeepingPkt_t_pb.Spare', index=6,
      number=7, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ChildQueueCount', full_name='FM_HousekeepingPkt_t_pb.ChildQueueCount', index=7,
      number=8, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ChildPreviousCC', full_name='FM_HousekeepingPkt_t_pb.ChildPreviousCC', index=8,
      number=9, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ChildCmdCounter', full_name='FM_HousekeepingPkt_t_pb.ChildCmdCounter', index=9,
      number=10, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ChildCmdErrCounter', full_name='FM_HousekeepingPkt_t_pb.ChildCmdErrCounter', index=10,
      number=11, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=323,
)

DESCRIPTOR.message_types_by_name['FM_HousekeepingPkt_t_pb'] = _FM_HOUSEKEEPINGPKT_T_PB

FM_HousekeepingPkt_t_pb = _reflection.GeneratedProtocolMessageType('FM_HousekeepingPkt_t_pb', (_message.Message,), dict(
  DESCRIPTOR = _FM_HOUSEKEEPINGPKT_T_PB,
  __module__ = '_py_FM_HousekeepingPkt_t_pb2'
  # @@protoc_insertion_point(class_scope:FM_HousekeepingPkt_t_pb)
  ))
_sym_db.RegisterMessage(FM_HousekeepingPkt_t_pb)


# @@protoc_insertion_point(module_scope)
