# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: _py_GPS_NAV_SVINFO_Combined_t.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='_py_GPS_NAV_SVINFO_Combined_t.proto',
  package='',
  serialized_pb=_b('\n#_py_GPS_NAV_SVINFO_Combined_t.proto\"]\n\x16GPS_NAV_SVINFO_P1_t_pb\x12\x13\n\x0bglobalFlags\x18\x01 \x02(\r\x12\r\n\x05numCh\x18\x02 \x02(\r\x12\x0c\n\x04iTOW\x18\x03 \x02(\r\x12\x11\n\treserved2\x18\x04 \x02(\r\"\x8b\x01\n\x16GPS_NAV_SVINFO_P2_t_pb\x12\x0c\n\x04svid\x18\x01 \x02(\r\x12\x0b\n\x03\x63hn\x18\x02 \x02(\r\x12\x0c\n\x04\x61zim\x18\x03 \x02(\x05\x12\r\n\x05\x66lags\x18\x04 \x02(\r\x12\x0c\n\x04\x65lev\x18\x05 \x02(\x05\x12\x0b\n\x03\x63no\x18\x06 \x02(\r\x12\x0f\n\x07quality\x18\x07 \x02(\r\x12\r\n\x05prRes\x18\x08 \x02(\x05\"o\n\x1cGPS_NAV_SVINFO_Combined_t_pb\x12\'\n\x06svinfo\x18\x01 \x02(\x0b\x32\x17.GPS_NAV_SVINFO_P1_t_pb\x12&\n\x05numCh\x18\x02 \x03(\x0b\x32\x17.GPS_NAV_SVINFO_P2_t_pb')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GPS_NAV_SVINFO_P1_T_PB = _descriptor.Descriptor(
  name='GPS_NAV_SVINFO_P1_t_pb',
  full_name='GPS_NAV_SVINFO_P1_t_pb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='globalFlags', full_name='GPS_NAV_SVINFO_P1_t_pb.globalFlags', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='numCh', full_name='GPS_NAV_SVINFO_P1_t_pb.numCh', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='iTOW', full_name='GPS_NAV_SVINFO_P1_t_pb.iTOW', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reserved2', full_name='GPS_NAV_SVINFO_P1_t_pb.reserved2', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=132,
)


_GPS_NAV_SVINFO_P2_T_PB = _descriptor.Descriptor(
  name='GPS_NAV_SVINFO_P2_t_pb',
  full_name='GPS_NAV_SVINFO_P2_t_pb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='svid', full_name='GPS_NAV_SVINFO_P2_t_pb.svid', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='chn', full_name='GPS_NAV_SVINFO_P2_t_pb.chn', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='azim', full_name='GPS_NAV_SVINFO_P2_t_pb.azim', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='flags', full_name='GPS_NAV_SVINFO_P2_t_pb.flags', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='elev', full_name='GPS_NAV_SVINFO_P2_t_pb.elev', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cno', full_name='GPS_NAV_SVINFO_P2_t_pb.cno', index=5,
      number=6, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='quality', full_name='GPS_NAV_SVINFO_P2_t_pb.quality', index=6,
      number=7, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='prRes', full_name='GPS_NAV_SVINFO_P2_t_pb.prRes', index=7,
      number=8, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=274,
)


_GPS_NAV_SVINFO_COMBINED_T_PB = _descriptor.Descriptor(
  name='GPS_NAV_SVINFO_Combined_t_pb',
  full_name='GPS_NAV_SVINFO_Combined_t_pb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='svinfo', full_name='GPS_NAV_SVINFO_Combined_t_pb.svinfo', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='numCh', full_name='GPS_NAV_SVINFO_Combined_t_pb.numCh', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=276,
  serialized_end=387,
)

_GPS_NAV_SVINFO_COMBINED_T_PB.fields_by_name['svinfo'].message_type = _GPS_NAV_SVINFO_P1_T_PB
_GPS_NAV_SVINFO_COMBINED_T_PB.fields_by_name['numCh'].message_type = _GPS_NAV_SVINFO_P2_T_PB
DESCRIPTOR.message_types_by_name['GPS_NAV_SVINFO_P1_t_pb'] = _GPS_NAV_SVINFO_P1_T_PB
DESCRIPTOR.message_types_by_name['GPS_NAV_SVINFO_P2_t_pb'] = _GPS_NAV_SVINFO_P2_T_PB
DESCRIPTOR.message_types_by_name['GPS_NAV_SVINFO_Combined_t_pb'] = _GPS_NAV_SVINFO_COMBINED_T_PB

GPS_NAV_SVINFO_P1_t_pb = _reflection.GeneratedProtocolMessageType('GPS_NAV_SVINFO_P1_t_pb', (_message.Message,), dict(
  DESCRIPTOR = _GPS_NAV_SVINFO_P1_T_PB,
  __module__ = '_py_GPS_NAV_SVINFO_Combined_t_pb2'
  # @@protoc_insertion_point(class_scope:GPS_NAV_SVINFO_P1_t_pb)
  ))
_sym_db.RegisterMessage(GPS_NAV_SVINFO_P1_t_pb)

GPS_NAV_SVINFO_P2_t_pb = _reflection.GeneratedProtocolMessageType('GPS_NAV_SVINFO_P2_t_pb', (_message.Message,), dict(
  DESCRIPTOR = _GPS_NAV_SVINFO_P2_T_PB,
  __module__ = '_py_GPS_NAV_SVINFO_Combined_t_pb2'
  # @@protoc_insertion_point(class_scope:GPS_NAV_SVINFO_P2_t_pb)
  ))
_sym_db.RegisterMessage(GPS_NAV_SVINFO_P2_t_pb)

GPS_NAV_SVINFO_Combined_t_pb = _reflection.GeneratedProtocolMessageType('GPS_NAV_SVINFO_Combined_t_pb', (_message.Message,), dict(
  DESCRIPTOR = _GPS_NAV_SVINFO_COMBINED_T_PB,
  __module__ = '_py_GPS_NAV_SVINFO_Combined_t_pb2'
  # @@protoc_insertion_point(class_scope:GPS_NAV_SVINFO_Combined_t_pb)
  ))
_sym_db.RegisterMessage(GPS_NAV_SVINFO_Combined_t_pb)


# @@protoc_insertion_point(module_scope)
