# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: _py_GPS_NAV_SOL_t.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='_py_GPS_NAV_SOL_t.proto',
  package='',
  serialized_pb=_b('\n\x17_py_GPS_NAV_SOL_t.proto\"\xf1\x01\n\x10GPS_NAV_SOL_t_pb\x12\x0c\n\x04week\x18\x01 \x02(\x05\x12\x0e\n\x06gpsFix\x18\x02 \x02(\r\x12\x0c\n\x04\x66TOW\x18\x03 \x02(\x05\x12\x0c\n\x04sAcc\x18\x04 \x02(\r\x12\x0c\n\x04pAcc\x18\x05 \x02(\r\x12\x0c\n\x04pDOP\x18\x06 \x02(\r\x12\r\n\x05\x65\x63\x65\x66Z\x18\x07 \x02(\x05\x12\r\n\x05\x65\x63\x65\x66X\x18\x08 \x02(\x05\x12\r\n\x05\x65\x63\x65\x66Y\x18\t \x02(\x05\x12\x0e\n\x06\x65\x63\x65\x66VY\x18\n \x02(\x05\x12\x0e\n\x06\x65\x63\x65\x66VX\x18\x0b \x02(\x05\x12\x0e\n\x06\x65\x63\x65\x66VZ\x18\x0c \x02(\x05\x12\r\n\x05\x66lags\x18\r \x02(\r\x12\r\n\x05numSV\x18\x0e \x02(\r\x12\x0c\n\x04iTOW\x18\x0f \x02(\r')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GPS_NAV_SOL_T_PB = _descriptor.Descriptor(
  name='GPS_NAV_SOL_t_pb',
  full_name='GPS_NAV_SOL_t_pb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='week', full_name='GPS_NAV_SOL_t_pb.week', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gpsFix', full_name='GPS_NAV_SOL_t_pb.gpsFix', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fTOW', full_name='GPS_NAV_SOL_t_pb.fTOW', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sAcc', full_name='GPS_NAV_SOL_t_pb.sAcc', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pAcc', full_name='GPS_NAV_SOL_t_pb.pAcc', index=4,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pDOP', full_name='GPS_NAV_SOL_t_pb.pDOP', index=5,
      number=6, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ecefZ', full_name='GPS_NAV_SOL_t_pb.ecefZ', index=6,
      number=7, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ecefX', full_name='GPS_NAV_SOL_t_pb.ecefX', index=7,
      number=8, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ecefY', full_name='GPS_NAV_SOL_t_pb.ecefY', index=8,
      number=9, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ecefVY', full_name='GPS_NAV_SOL_t_pb.ecefVY', index=9,
      number=10, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ecefVX', full_name='GPS_NAV_SOL_t_pb.ecefVX', index=10,
      number=11, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ecefVZ', full_name='GPS_NAV_SOL_t_pb.ecefVZ', index=11,
      number=12, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='flags', full_name='GPS_NAV_SOL_t_pb.flags', index=12,
      number=13, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='numSV', full_name='GPS_NAV_SOL_t_pb.numSV', index=13,
      number=14, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='iTOW', full_name='GPS_NAV_SOL_t_pb.iTOW', index=14,
      number=15, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=269,
)

DESCRIPTOR.message_types_by_name['GPS_NAV_SOL_t_pb'] = _GPS_NAV_SOL_T_PB

GPS_NAV_SOL_t_pb = _reflection.GeneratedProtocolMessageType('GPS_NAV_SOL_t_pb', (_message.Message,), dict(
  DESCRIPTOR = _GPS_NAV_SOL_T_PB,
  __module__ = '_py_GPS_NAV_SOL_t_pb2'
  # @@protoc_insertion_point(class_scope:GPS_NAV_SOL_t_pb)
  ))
_sym_db.RegisterMessage(GPS_NAV_SOL_t_pb)


# @@protoc_insertion_point(module_scope)
