# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: _py_HMC5883_ConfigTbl_t.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='_py_HMC5883_ConfigTbl_t.proto',
  package='',
  serialized_pb=_b('\n\x1d_py_HMC5883_ConfigTbl_t.proto\"\x81\x01\n\x16HMC5883_ConfigTbl_t_pb\x12\x0f\n\x07y_scale\x18\x01 \x02(\x02\x12\x10\n\x08y_offset\x18\x02 \x02(\x02\x12\x10\n\x08x_offset\x18\x03 \x02(\x02\x12\x10\n\x08z_offset\x18\x04 \x02(\x02\x12\x0f\n\x07x_scale\x18\x05 \x02(\x02\x12\x0f\n\x07z_scale\x18\x06 \x02(\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_HMC5883_CONFIGTBL_T_PB = _descriptor.Descriptor(
  name='HMC5883_ConfigTbl_t_pb',
  full_name='HMC5883_ConfigTbl_t_pb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='y_scale', full_name='HMC5883_ConfigTbl_t_pb.y_scale', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y_offset', full_name='HMC5883_ConfigTbl_t_pb.y_offset', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='x_offset', full_name='HMC5883_ConfigTbl_t_pb.x_offset', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z_offset', full_name='HMC5883_ConfigTbl_t_pb.z_offset', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='x_scale', full_name='HMC5883_ConfigTbl_t_pb.x_scale', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z_scale', full_name='HMC5883_ConfigTbl_t_pb.z_scale', index=5,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=163,
)

DESCRIPTOR.message_types_by_name['HMC5883_ConfigTbl_t_pb'] = _HMC5883_CONFIGTBL_T_PB

HMC5883_ConfigTbl_t_pb = _reflection.GeneratedProtocolMessageType('HMC5883_ConfigTbl_t_pb', (_message.Message,), dict(
  DESCRIPTOR = _HMC5883_CONFIGTBL_T_PB,
  __module__ = '_py_HMC5883_ConfigTbl_t_pb2'
  # @@protoc_insertion_point(class_scope:HMC5883_ConfigTbl_t_pb)
  ))
_sym_db.RegisterMessage(HMC5883_ConfigTbl_t_pb)


# @@protoc_insertion_point(module_scope)
