# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: _py_MM_HkPacket_t.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='_py_MM_HkPacket_t.proto',
  package='',
  serialized_pb=_b('\n\x17_py_MM_HkPacket_t.proto\"\xc0\x01\n\x10MM_HkPacket_t_pb\x12\x0f\n\x07MemType\x18\x01 \x02(\r\x12\x11\n\tDataValue\x18\x02 \x02(\r\x12\x12\n\nCmdCounter\x18\x03 \x02(\r\x12\x10\n\x08\x46ileName\x18\x04 \x02(\t\x12\x12\n\nErrCounter\x18\x05 \x02(\r\x12\x11\n\tTlmHeader\x18\x06 \x03(\r\x12\x12\n\nLastAction\x18\x07 \x02(\r\x12\x16\n\x0e\x42ytesProcessed\x18\x08 \x02(\r\x12\x0f\n\x07\x41\x64\x64ress\x18\t \x02(\r')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MM_HKPACKET_T_PB = _descriptor.Descriptor(
  name='MM_HkPacket_t_pb',
  full_name='MM_HkPacket_t_pb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='MemType', full_name='MM_HkPacket_t_pb.MemType', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DataValue', full_name='MM_HkPacket_t_pb.DataValue', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='CmdCounter', full_name='MM_HkPacket_t_pb.CmdCounter', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='FileName', full_name='MM_HkPacket_t_pb.FileName', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ErrCounter', full_name='MM_HkPacket_t_pb.ErrCounter', index=4,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='TlmHeader', full_name='MM_HkPacket_t_pb.TlmHeader', index=5,
      number=6, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='LastAction', full_name='MM_HkPacket_t_pb.LastAction', index=6,
      number=7, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='BytesProcessed', full_name='MM_HkPacket_t_pb.BytesProcessed', index=7,
      number=8, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Address', full_name='MM_HkPacket_t_pb.Address', index=8,
      number=9, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=220,
)

DESCRIPTOR.message_types_by_name['MM_HkPacket_t_pb'] = _MM_HKPACKET_T_PB

MM_HkPacket_t_pb = _reflection.GeneratedProtocolMessageType('MM_HkPacket_t_pb', (_message.Message,), dict(
  DESCRIPTOR = _MM_HKPACKET_T_PB,
  __module__ = '_py_MM_HkPacket_t_pb2'
  # @@protoc_insertion_point(class_scope:MM_HkPacket_t_pb)
  ))
_sym_db.RegisterMessage(MM_HkPacket_t_pb)


# @@protoc_insertion_point(module_scope)
