# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: _py_MPC_ConfigTbl_t.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='_py_MPC_ConfigTbl_t.proto',
  package='',
  serialized_pb=_b('\n\x19_py_MPC_ConfigTbl_t.proto\"\xf8\x06\n\x12MPC_ConfigTbl_t_pb\x12\x12\n\nXY_VEL_MAX\x18\x01 \x02(\x02\x12\x12\n\nACC_UP_MAX\x18\x02 \x02(\x02\x12\x14\n\x0cMAN_TILT_MAX\x18\x03 \x02(\x02\x12\x11\n\tTHR_HOVER\x18\x04 \x02(\x02\x12\x12\n\nMANTHR_MIN\x18\x05 \x02(\x02\x12\x0c\n\x04XY_P\x18\x06 \x02(\x02\x12\x11\n\tTKO_SPEED\x18\x07 \x02(\x02\x12\x11\n\tXY_CRUISE\x18\x08 \x02(\x02\x12\x0f\n\x07HOLD_DZ\x18\t \x02(\x02\x12\x10\n\x08\x41LT_MODE\x18\n \x02(\r\x12\x13\n\x0bHOLD_MAX_XY\x18\x0b \x02(\x02\x12\x17\n\x0fVT_OPT_RECOV_EN\x18\x0c \x02(\x05\x12\x12\n\nTKO_RAMP_T\x18\r \x02(\x02\x12\x11\n\tLAND_ALT1\x18\x0e \x02(\r\x12\x11\n\tLAND_ALT2\x18\x0f \x02(\r\x12\x14\n\x0cZ_VEL_MAX_UP\x18\x10 \x02(\x02\x12\x10\n\x08MC_YAW_P\x18\x11 \x02(\x02\x12\x12\n\nMANTHR_MAX\x18\x12 \x02(\x02\x12\x12\n\nHOLD_MAX_Z\x18\x13 \x02(\x02\x12\x12\n\nLAND_SPEED\x18\x14 \x02(\x02\x12\x14\n\x0cZ_VEL_MAX_DN\x18\x15 \x02(\x02\x12\r\n\x05XY_FF\x18\x16 \x02(\x02\x12\x13\n\x0bTILTMAX_LND\x18\x17 \x02(\x02\x12\x0f\n\x07Z_VEL_P\x18\x18 \x02(\x02\x12\x13\n\x0bTARGET_THRE\x18\x19 \x02(\x02\x12\x12\n\nZ_MAN_EXPO\x18\x1a \x02(\x02\x12\x13\n\x0bVEL_MAN_MAX\x18\x1b \x02(\x02\x12\x0f\n\x07Z_VEL_I\x18\x1c \x02(\x02\x12\x13\n\x0bTILTMAX_AIR\x18\x1d \x02(\x02\x12\x0f\n\x07Z_VEL_D\x18\x1e \x02(\x02\x12\x0f\n\x07VELD_LP\x18\x1f \x02(\x02\x12\x11\n\tMAN_Y_MAX\x18  \x02(\x02\x12\x0c\n\x04Z_FF\x18! \x02(\x02\x12\x0b\n\x03Z_P\x18\" \x02(\x02\x12\x10\n\x08XY_VEL_I\x18# \x02(\x02\x12\x13\n\x0bXY_MAN_EXPO\x18$ \x02(\r\x12\x16\n\x0eMC_YAWRATE_MAX\x18% \x02(\x02\x12\x16\n\x0eMIS_LTRMIN_ALT\x18& \x02(\x02\x12\x10\n\x08XY_VEL_D\x18\' \x02(\x02\x12\x13\n\x0b\x41\x43\x43_HOR_MAX\x18( \x02(\x02\x12\x14\n\x0c\x41\x43\x43_DOWN_MAX\x18) \x02(\x02\x12\x13\n\x0b\x44\x45\x43_HOR_MAX\x18* \x02(\x02\x12\x0f\n\x07THR_MIN\x18+ \x02(\x02\x12\x10\n\x08XY_VEL_P\x18, \x02(\x02\x12\x0f\n\x07THR_MAX\x18- \x02(\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MPC_CONFIGTBL_T_PB = _descriptor.Descriptor(
  name='MPC_ConfigTbl_t_pb',
  full_name='MPC_ConfigTbl_t_pb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='XY_VEL_MAX', full_name='MPC_ConfigTbl_t_pb.XY_VEL_MAX', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ACC_UP_MAX', full_name='MPC_ConfigTbl_t_pb.ACC_UP_MAX', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='MAN_TILT_MAX', full_name='MPC_ConfigTbl_t_pb.MAN_TILT_MAX', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='THR_HOVER', full_name='MPC_ConfigTbl_t_pb.THR_HOVER', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='MANTHR_MIN', full_name='MPC_ConfigTbl_t_pb.MANTHR_MIN', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='XY_P', full_name='MPC_ConfigTbl_t_pb.XY_P', index=5,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='TKO_SPEED', full_name='MPC_ConfigTbl_t_pb.TKO_SPEED', index=6,
      number=7, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='XY_CRUISE', full_name='MPC_ConfigTbl_t_pb.XY_CRUISE', index=7,
      number=8, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='HOLD_DZ', full_name='MPC_ConfigTbl_t_pb.HOLD_DZ', index=8,
      number=9, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ALT_MODE', full_name='MPC_ConfigTbl_t_pb.ALT_MODE', index=9,
      number=10, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='HOLD_MAX_XY', full_name='MPC_ConfigTbl_t_pb.HOLD_MAX_XY', index=10,
      number=11, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='VT_OPT_RECOV_EN', full_name='MPC_ConfigTbl_t_pb.VT_OPT_RECOV_EN', index=11,
      number=12, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='TKO_RAMP_T', full_name='MPC_ConfigTbl_t_pb.TKO_RAMP_T', index=12,
      number=13, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='LAND_ALT1', full_name='MPC_ConfigTbl_t_pb.LAND_ALT1', index=13,
      number=14, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='LAND_ALT2', full_name='MPC_ConfigTbl_t_pb.LAND_ALT2', index=14,
      number=15, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Z_VEL_MAX_UP', full_name='MPC_ConfigTbl_t_pb.Z_VEL_MAX_UP', index=15,
      number=16, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='MC_YAW_P', full_name='MPC_ConfigTbl_t_pb.MC_YAW_P', index=16,
      number=17, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='MANTHR_MAX', full_name='MPC_ConfigTbl_t_pb.MANTHR_MAX', index=17,
      number=18, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='HOLD_MAX_Z', full_name='MPC_ConfigTbl_t_pb.HOLD_MAX_Z', index=18,
      number=19, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='LAND_SPEED', full_name='MPC_ConfigTbl_t_pb.LAND_SPEED', index=19,
      number=20, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Z_VEL_MAX_DN', full_name='MPC_ConfigTbl_t_pb.Z_VEL_MAX_DN', index=20,
      number=21, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='XY_FF', full_name='MPC_ConfigTbl_t_pb.XY_FF', index=21,
      number=22, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='TILTMAX_LND', full_name='MPC_ConfigTbl_t_pb.TILTMAX_LND', index=22,
      number=23, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Z_VEL_P', full_name='MPC_ConfigTbl_t_pb.Z_VEL_P', index=23,
      number=24, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='TARGET_THRE', full_name='MPC_ConfigTbl_t_pb.TARGET_THRE', index=24,
      number=25, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Z_MAN_EXPO', full_name='MPC_ConfigTbl_t_pb.Z_MAN_EXPO', index=25,
      number=26, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='VEL_MAN_MAX', full_name='MPC_ConfigTbl_t_pb.VEL_MAN_MAX', index=26,
      number=27, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Z_VEL_I', full_name='MPC_ConfigTbl_t_pb.Z_VEL_I', index=27,
      number=28, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='TILTMAX_AIR', full_name='MPC_ConfigTbl_t_pb.TILTMAX_AIR', index=28,
      number=29, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Z_VEL_D', full_name='MPC_ConfigTbl_t_pb.Z_VEL_D', index=29,
      number=30, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='VELD_LP', full_name='MPC_ConfigTbl_t_pb.VELD_LP', index=30,
      number=31, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='MAN_Y_MAX', full_name='MPC_ConfigTbl_t_pb.MAN_Y_MAX', index=31,
      number=32, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Z_FF', full_name='MPC_ConfigTbl_t_pb.Z_FF', index=32,
      number=33, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Z_P', full_name='MPC_ConfigTbl_t_pb.Z_P', index=33,
      number=34, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='XY_VEL_I', full_name='MPC_ConfigTbl_t_pb.XY_VEL_I', index=34,
      number=35, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='XY_MAN_EXPO', full_name='MPC_ConfigTbl_t_pb.XY_MAN_EXPO', index=35,
      number=36, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='MC_YAWRATE_MAX', full_name='MPC_ConfigTbl_t_pb.MC_YAWRATE_MAX', index=36,
      number=37, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='MIS_LTRMIN_ALT', full_name='MPC_ConfigTbl_t_pb.MIS_LTRMIN_ALT', index=37,
      number=38, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='XY_VEL_D', full_name='MPC_ConfigTbl_t_pb.XY_VEL_D', index=38,
      number=39, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ACC_HOR_MAX', full_name='MPC_ConfigTbl_t_pb.ACC_HOR_MAX', index=39,
      number=40, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ACC_DOWN_MAX', full_name='MPC_ConfigTbl_t_pb.ACC_DOWN_MAX', index=40,
      number=41, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DEC_HOR_MAX', full_name='MPC_ConfigTbl_t_pb.DEC_HOR_MAX', index=41,
      number=42, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='THR_MIN', full_name='MPC_ConfigTbl_t_pb.THR_MIN', index=42,
      number=43, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='XY_VEL_P', full_name='MPC_ConfigTbl_t_pb.XY_VEL_P', index=43,
      number=44, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='THR_MAX', full_name='MPC_ConfigTbl_t_pb.THR_MAX', index=44,
      number=45, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=918,
)

DESCRIPTOR.message_types_by_name['MPC_ConfigTbl_t_pb'] = _MPC_CONFIGTBL_T_PB

MPC_ConfigTbl_t_pb = _reflection.GeneratedProtocolMessageType('MPC_ConfigTbl_t_pb', (_message.Message,), dict(
  DESCRIPTOR = _MPC_CONFIGTBL_T_PB,
  __module__ = '_py_MPC_ConfigTbl_t_pb2'
  # @@protoc_insertion_point(class_scope:MPC_ConfigTbl_t_pb)
  ))
_sym_db.RegisterMessage(MPC_ConfigTbl_t_pb)


# @@protoc_insertion_point(module_scope)
