# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: _py_PX4_VehicleLandDetectedMsg_t.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='_py_PX4_VehicleLandDetectedMsg_t.proto',
  package='',
  serialized_pb=_b('\n&_py_PX4_VehicleLandDetectedMsg_t.proto\"\x90\x01\n\x1fPX4_VehicleLandDetectedMsg_t_pb\x12\x10\n\x08\x46reefall\x18\x01 \x02(\x08\x12\x0e\n\x06\x41ltMax\x18\x02 \x02(\x02\x12\x11\n\tTimestamp\x18\x03 \x02(\x04\x12\x0e\n\x06Landed\x18\x04 \x02(\x08\x12\x15\n\rGroundContact\x18\x05 \x02(\x08\x12\x11\n\tTlmHeader\x18\x06 \x03(\r')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PX4_VEHICLELANDDETECTEDMSG_T_PB = _descriptor.Descriptor(
  name='PX4_VehicleLandDetectedMsg_t_pb',
  full_name='PX4_VehicleLandDetectedMsg_t_pb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Freefall', full_name='PX4_VehicleLandDetectedMsg_t_pb.Freefall', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='AltMax', full_name='PX4_VehicleLandDetectedMsg_t_pb.AltMax', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Timestamp', full_name='PX4_VehicleLandDetectedMsg_t_pb.Timestamp', index=2,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Landed', full_name='PX4_VehicleLandDetectedMsg_t_pb.Landed', index=3,
      number=4, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='GroundContact', full_name='PX4_VehicleLandDetectedMsg_t_pb.GroundContact', index=4,
      number=5, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='TlmHeader', full_name='PX4_VehicleLandDetectedMsg_t_pb.TlmHeader', index=5,
      number=6, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=187,
)

DESCRIPTOR.message_types_by_name['PX4_VehicleLandDetectedMsg_t_pb'] = _PX4_VEHICLELANDDETECTEDMSG_T_PB

PX4_VehicleLandDetectedMsg_t_pb = _reflection.GeneratedProtocolMessageType('PX4_VehicleLandDetectedMsg_t_pb', (_message.Message,), dict(
  DESCRIPTOR = _PX4_VEHICLELANDDETECTEDMSG_T_PB,
  __module__ = '_py_PX4_VehicleLandDetectedMsg_t_pb2'
  # @@protoc_insertion_point(class_scope:PX4_VehicleLandDetectedMsg_t_pb)
  ))
_sym_db.RegisterMessage(PX4_VehicleLandDetectedMsg_t_pb)


# @@protoc_insertion_point(module_scope)
