# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: _py_PX4_VehicleLocalPositionSetpointMsg_t.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='_py_PX4_VehicleLocalPositionSetpointMsg_t.proto',
  package='',
  serialized_pb=_b('\n/_py_PX4_VehicleLocalPositionSetpointMsg_t.proto\"\xcc\x01\n(PX4_VehicleLocalPositionSetpointMsg_t_pb\x12\n\n\x02VY\x18\x01 \x02(\x02\x12\x11\n\tTimestamp\x18\x02 \x02(\x04\x12\x0b\n\x03Yaw\x18\x03 \x02(\x02\x12\n\n\x02VX\x18\x04 \x02(\x02\x12\x11\n\tTlmHeader\x18\x05 \x03(\r\x12\x0c\n\x04\x41\x63\x63Y\x18\x06 \x02(\x02\x12\x0c\n\x04\x41\x63\x63X\x18\x07 \x02(\x02\x12\x0c\n\x04\x41\x63\x63Z\x18\x08 \x02(\x02\x12\t\n\x01Y\x18\t \x02(\x02\x12\t\n\x01X\x18\n \x02(\x02\x12\n\n\x02VZ\x18\x0b \x02(\x02\x12\t\n\x01Z\x18\x0c \x02(\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PX4_VEHICLELOCALPOSITIONSETPOINTMSG_T_PB = _descriptor.Descriptor(
  name='PX4_VehicleLocalPositionSetpointMsg_t_pb',
  full_name='PX4_VehicleLocalPositionSetpointMsg_t_pb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='VY', full_name='PX4_VehicleLocalPositionSetpointMsg_t_pb.VY', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Timestamp', full_name='PX4_VehicleLocalPositionSetpointMsg_t_pb.Timestamp', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Yaw', full_name='PX4_VehicleLocalPositionSetpointMsg_t_pb.Yaw', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='VX', full_name='PX4_VehicleLocalPositionSetpointMsg_t_pb.VX', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='TlmHeader', full_name='PX4_VehicleLocalPositionSetpointMsg_t_pb.TlmHeader', index=4,
      number=5, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='AccY', full_name='PX4_VehicleLocalPositionSetpointMsg_t_pb.AccY', index=5,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='AccX', full_name='PX4_VehicleLocalPositionSetpointMsg_t_pb.AccX', index=6,
      number=7, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='AccZ', full_name='PX4_VehicleLocalPositionSetpointMsg_t_pb.AccZ', index=7,
      number=8, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Y', full_name='PX4_VehicleLocalPositionSetpointMsg_t_pb.Y', index=8,
      number=9, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='X', full_name='PX4_VehicleLocalPositionSetpointMsg_t_pb.X', index=9,
      number=10, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='VZ', full_name='PX4_VehicleLocalPositionSetpointMsg_t_pb.VZ', index=10,
      number=11, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Z', full_name='PX4_VehicleLocalPositionSetpointMsg_t_pb.Z', index=11,
      number=12, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=256,
)

DESCRIPTOR.message_types_by_name['PX4_VehicleLocalPositionSetpointMsg_t_pb'] = _PX4_VEHICLELOCALPOSITIONSETPOINTMSG_T_PB

PX4_VehicleLocalPositionSetpointMsg_t_pb = _reflection.GeneratedProtocolMessageType('PX4_VehicleLocalPositionSetpointMsg_t_pb', (_message.Message,), dict(
  DESCRIPTOR = _PX4_VEHICLELOCALPOSITIONSETPOINTMSG_T_PB,
  __module__ = '_py_PX4_VehicleLocalPositionSetpointMsg_t_pb2'
  # @@protoc_insertion_point(class_scope:PX4_VehicleLocalPositionSetpointMsg_t_pb)
  ))
_sym_db.RegisterMessage(PX4_VehicleLocalPositionSetpointMsg_t_pb)


# @@protoc_insertion_point(module_scope)
