# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: _py_PX4_SensorAccelMsg_t.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='_py_PX4_SensorAccelMsg_t.proto',
  package='',
  serialized_pb=_b('\n\x1e_py_PX4_SensorAccelMsg_t.proto\"\xcf\x02\n\x17PX4_SensorAccelMsg_t_pb\x12\x16\n\x0eTemperatureRaw\x18\x01 \x02(\x05\x12\x11\n\tZIntegral\x18\x02 \x02(\x02\x12\x13\n\x0bTemperature\x18\x03 \x02(\x02\x12\x12\n\nIntegralDt\x18\x04 \x02(\x04\x12\x11\n\tTimestamp\x18\x05 \x02(\x04\x12\x12\n\nRange_m_s2\x18\x06 \x02(\x02\x12\x0c\n\x04ZRaw\x18\x07 \x02(\x05\x12\x0c\n\x04YRaw\x18\x08 \x02(\x05\x12\x0f\n\x07Scaling\x18\t \x02(\x02\x12\x11\n\tTlmHeader\x18\n \x03(\r\x12\x11\n\tYIntegral\x18\x0b \x02(\x02\x12\x10\n\x08\x44\x65viceID\x18\x0c \x02(\r\x12\t\n\x01Y\x18\r \x02(\x02\x12\t\n\x01X\x18\x0e \x02(\x02\x12\t\n\x01Z\x18\x0f \x02(\x02\x12\x12\n\nErrorCount\x18\x10 \x02(\x04\x12\x0c\n\x04XRaw\x18\x11 \x02(\x05\x12\x11\n\tXIntegral\x18\x12 \x02(\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PX4_SENSORACCELMSG_T_PB = _descriptor.Descriptor(
  name='PX4_SensorAccelMsg_t_pb',
  full_name='PX4_SensorAccelMsg_t_pb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='TemperatureRaw', full_name='PX4_SensorAccelMsg_t_pb.TemperatureRaw', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ZIntegral', full_name='PX4_SensorAccelMsg_t_pb.ZIntegral', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Temperature', full_name='PX4_SensorAccelMsg_t_pb.Temperature', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='IntegralDt', full_name='PX4_SensorAccelMsg_t_pb.IntegralDt', index=3,
      number=4, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Timestamp', full_name='PX4_SensorAccelMsg_t_pb.Timestamp', index=4,
      number=5, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Range_m_s2', full_name='PX4_SensorAccelMsg_t_pb.Range_m_s2', index=5,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ZRaw', full_name='PX4_SensorAccelMsg_t_pb.ZRaw', index=6,
      number=7, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='YRaw', full_name='PX4_SensorAccelMsg_t_pb.YRaw', index=7,
      number=8, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Scaling', full_name='PX4_SensorAccelMsg_t_pb.Scaling', index=8,
      number=9, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='TlmHeader', full_name='PX4_SensorAccelMsg_t_pb.TlmHeader', index=9,
      number=10, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='YIntegral', full_name='PX4_SensorAccelMsg_t_pb.YIntegral', index=10,
      number=11, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DeviceID', full_name='PX4_SensorAccelMsg_t_pb.DeviceID', index=11,
      number=12, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Y', full_name='PX4_SensorAccelMsg_t_pb.Y', index=12,
      number=13, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='X', full_name='PX4_SensorAccelMsg_t_pb.X', index=13,
      number=14, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Z', full_name='PX4_SensorAccelMsg_t_pb.Z', index=14,
      number=15, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ErrorCount', full_name='PX4_SensorAccelMsg_t_pb.ErrorCount', index=15,
      number=16, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='XRaw', full_name='PX4_SensorAccelMsg_t_pb.XRaw', index=16,
      number=17, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='XIntegral', full_name='PX4_SensorAccelMsg_t_pb.XIntegral', index=17,
      number=18, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=370,
)

DESCRIPTOR.message_types_by_name['PX4_SensorAccelMsg_t_pb'] = _PX4_SENSORACCELMSG_T_PB

PX4_SensorAccelMsg_t_pb = _reflection.GeneratedProtocolMessageType('PX4_SensorAccelMsg_t_pb', (_message.Message,), dict(
  DESCRIPTOR = _PX4_SENSORACCELMSG_T_PB,
  __module__ = '_py_PX4_SensorAccelMsg_t_pb2'
  # @@protoc_insertion_point(class_scope:PX4_SensorAccelMsg_t_pb)
  ))
_sym_db.RegisterMessage(PX4_SensorAccelMsg_t_pb)


# @@protoc_insertion_point(module_scope)
