# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: _py_PX4_RcChannelsMsg_t.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='_py_PX4_RcChannelsMsg_t.proto',
  package='',
  serialized_pb=_b('\n\x1d_py_PX4_RcChannelsMsg_t.proto\"\xce\x01\n\x16PX4_RcChannelsMsg_t_pb\x12\x10\n\x08\x46unction\x18\x01 \x03(\r\x12\x14\n\x0c\x43hannelCount\x18\x02 \x02(\r\x12\x1a\n\x12TimestampLastValid\x18\x03 \x02(\x04\x12\x16\n\x0e\x46rameDropCount\x18\x04 \x02(\r\x12\x11\n\tTimestamp\x18\x05 \x02(\x04\x12\x10\n\x08\x43hannels\x18\x06 \x03(\x02\x12\x11\n\tTlmHeader\x18\x07 \x03(\r\x12\x0c\n\x04RSSI\x18\x08 \x02(\r\x12\x12\n\nSignalLost\x18\t \x02(\x08')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PX4_RCCHANNELSMSG_T_PB = _descriptor.Descriptor(
  name='PX4_RcChannelsMsg_t_pb',
  full_name='PX4_RcChannelsMsg_t_pb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Function', full_name='PX4_RcChannelsMsg_t_pb.Function', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ChannelCount', full_name='PX4_RcChannelsMsg_t_pb.ChannelCount', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='TimestampLastValid', full_name='PX4_RcChannelsMsg_t_pb.TimestampLastValid', index=2,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='FrameDropCount', full_name='PX4_RcChannelsMsg_t_pb.FrameDropCount', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Timestamp', full_name='PX4_RcChannelsMsg_t_pb.Timestamp', index=4,
      number=5, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Channels', full_name='PX4_RcChannelsMsg_t_pb.Channels', index=5,
      number=6, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='TlmHeader', full_name='PX4_RcChannelsMsg_t_pb.TlmHeader', index=6,
      number=7, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='RSSI', full_name='PX4_RcChannelsMsg_t_pb.RSSI', index=7,
      number=8, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SignalLost', full_name='PX4_RcChannelsMsg_t_pb.SignalLost', index=8,
      number=9, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=240,
)

DESCRIPTOR.message_types_by_name['PX4_RcChannelsMsg_t_pb'] = _PX4_RCCHANNELSMSG_T_PB

PX4_RcChannelsMsg_t_pb = _reflection.GeneratedProtocolMessageType('PX4_RcChannelsMsg_t_pb', (_message.Message,), dict(
  DESCRIPTOR = _PX4_RCCHANNELSMSG_T_PB,
  __module__ = '_py_PX4_RcChannelsMsg_t_pb2'
  # @@protoc_insertion_point(class_scope:PX4_RcChannelsMsg_t_pb)
  ))
_sym_db.RegisterMessage(PX4_RcChannelsMsg_t_pb)


# @@protoc_insertion_point(module_scope)
