# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: _py_SIMLIB_GPSData_t.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='_py_SIMLIB_GPSData_t.proto',
  package='',
  serialized_pb=_b('\n\x1a_py_SIMLIB_GPSData_t.proto\"\xe8\x01\n\x13SIMLIB_GPSData_t_pb\x12\n\n\x02VD\x18\x01 \x02(\x05\x12\x0b\n\x03\x43OG\x18\x02 \x02(\r\x12\x0f\n\x07\x46ixType\x18\x03 \x02(\r\x12\x0b\n\x03\x45PV\x18\x04 \x02(\r\x12\x19\n\x11SatellitesVisible\x18\x05 \x02(\r\x12\x10\n\x08\x41ltitude\x18\x06 \x02(\x05\x12\x11\n\tLongitude\x18\x07 \x02(\x05\x12\n\n\x02VN\x18\x08 \x02(\x05\x12\x11\n\tDataState\x18\t \x02(\r\x12\x10\n\x08Latitude\x18\n \x02(\x05\x12\x10\n\x08Velocity\x18\x0b \x02(\r\x12\x0b\n\x03\x45PH\x18\x0c \x02(\r\x12\n\n\x02VE\x18\r \x02(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SIMLIB_GPSDATA_T_PB = _descriptor.Descriptor(
  name='SIMLIB_GPSData_t_pb',
  full_name='SIMLIB_GPSData_t_pb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='VD', full_name='SIMLIB_GPSData_t_pb.VD', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='COG', full_name='SIMLIB_GPSData_t_pb.COG', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='FixType', full_name='SIMLIB_GPSData_t_pb.FixType', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='EPV', full_name='SIMLIB_GPSData_t_pb.EPV', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SatellitesVisible', full_name='SIMLIB_GPSData_t_pb.SatellitesVisible', index=4,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Altitude', full_name='SIMLIB_GPSData_t_pb.Altitude', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Longitude', full_name='SIMLIB_GPSData_t_pb.Longitude', index=6,
      number=7, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='VN', full_name='SIMLIB_GPSData_t_pb.VN', index=7,
      number=8, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DataState', full_name='SIMLIB_GPSData_t_pb.DataState', index=8,
      number=9, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Latitude', full_name='SIMLIB_GPSData_t_pb.Latitude', index=9,
      number=10, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Velocity', full_name='SIMLIB_GPSData_t_pb.Velocity', index=10,
      number=11, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='EPH', full_name='SIMLIB_GPSData_t_pb.EPH', index=11,
      number=12, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='VE', full_name='SIMLIB_GPSData_t_pb.VE', index=12,
      number=13, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=263,
)

DESCRIPTOR.message_types_by_name['SIMLIB_GPSData_t_pb'] = _SIMLIB_GPSDATA_T_PB

SIMLIB_GPSData_t_pb = _reflection.GeneratedProtocolMessageType('SIMLIB_GPSData_t_pb', (_message.Message,), dict(
  DESCRIPTOR = _SIMLIB_GPSDATA_T_PB,
  __module__ = '_py_SIMLIB_GPSData_t_pb2'
  # @@protoc_insertion_point(class_scope:SIMLIB_GPSData_t_pb)
  ))
_sym_db.RegisterMessage(SIMLIB_GPSData_t_pb)


# @@protoc_insertion_point(module_scope)
