/* This file was autogenerated from template version 0.0.0.1 and autogenerator version 0.0.0.1 */
#include "cfe_es_msg.h"
#include "pb.h"
#include "pb_encode.h"
#include "pb_decode.h"
#include "pb_lib.h"
#include "es_app_name.pb.h"
#include "es_query_all_tasks.pb.h"
#include "es_perf_set_trig_mask.pb.h"
#include "es_shell.pb.h"
#include "es_perf_start.pb.h"
#include "es_start_app.pb.h"
#include "es_dump_cds_reg.pb.h"
#include "es_delete_cds.pb.h"
#include "es_app_reload.pb.h"
#include "es_set_max_pr_count.pb.h"
#include "es_tlm_pool_stats_cmd.pb.h"
#include "es_hk.pb.h"
#include "es_perf_stop.pb.h"
#include "es_write_sys_log.pb.h"
#include "es_write_er_log.pb.h"
#include "es_query_all.pb.h"
#include "es_one_app.pb.h"
#include "es_shell_packet.pb.h"
#include "es_restart.pb.h"
#include "es_overwrite_sys_log.pb.h"
#include "es_perf_set_filter_mask.pb.h"

#ifdef __cplusplus
extern "C" {
#endif

uint32 CFE_ES_AppNameCmd_t_Enc(const CFE_ES_AppNameCmd_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 CFE_ES_AppNameCmd_t_Dec(const char *inBuffer, uint32 inSize, CFE_ES_AppNameCmd_t *inOutObject);

uint32 CFE_ES_QueryAllTasksCmd_t_Enc(const CFE_ES_QueryAllTasksCmd_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 CFE_ES_QueryAllTasksCmd_t_Dec(const char *inBuffer, uint32 inSize, CFE_ES_QueryAllTasksCmd_t *inOutObject);

uint32 CFE_ES_PerfSetTrigMaskCmd_t_Enc(const CFE_ES_PerfSetTrigMaskCmd_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 CFE_ES_PerfSetTrigMaskCmd_t_Dec(const char *inBuffer, uint32 inSize, CFE_ES_PerfSetTrigMaskCmd_t *inOutObject);

uint32 CFE_ES_ShellCmd_t_Enc(const CFE_ES_ShellCmd_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 CFE_ES_ShellCmd_t_Dec(const char *inBuffer, uint32 inSize, CFE_ES_ShellCmd_t *inOutObject);

uint32 CFE_ES_PerfStartCmd_t_Enc(const CFE_ES_PerfStartCmd_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 CFE_ES_PerfStartCmd_t_Dec(const char *inBuffer, uint32 inSize, CFE_ES_PerfStartCmd_t *inOutObject);

uint32 CFE_ES_StartAppCmd_t_Enc(const CFE_ES_StartAppCmd_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 CFE_ES_StartAppCmd_t_Dec(const char *inBuffer, uint32 inSize, CFE_ES_StartAppCmd_t *inOutObject);

uint32 CFE_ES_DumpCDSRegCmd_t_Enc(const CFE_ES_DumpCDSRegCmd_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 CFE_ES_DumpCDSRegCmd_t_Dec(const char *inBuffer, uint32 inSize, CFE_ES_DumpCDSRegCmd_t *inOutObject);

uint32 CFE_ES_DeleteCDSCmd_t_Enc(const CFE_ES_DeleteCDSCmd_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 CFE_ES_DeleteCDSCmd_t_Dec(const char *inBuffer, uint32 inSize, CFE_ES_DeleteCDSCmd_t *inOutObject);

uint32 CFE_ES_AppReloadCmd_t_Enc(const CFE_ES_AppReloadCmd_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 CFE_ES_AppReloadCmd_t_Dec(const char *inBuffer, uint32 inSize, CFE_ES_AppReloadCmd_t *inOutObject);

uint32 CFE_ES_SetMaxPRCountCmd_t_Enc(const CFE_ES_SetMaxPRCountCmd_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 CFE_ES_SetMaxPRCountCmd_t_Dec(const char *inBuffer, uint32 inSize, CFE_ES_SetMaxPRCountCmd_t *inOutObject);

uint32 CFE_ES_TlmPoolStatsCmd_t_Enc(const CFE_ES_TlmPoolStatsCmd_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 CFE_ES_TlmPoolStatsCmd_t_Dec(const char *inBuffer, uint32 inSize, CFE_ES_TlmPoolStatsCmd_t *inOutObject);

uint32 CFE_ES_HkPacket_t_Enc(const CFE_ES_HkPacket_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 CFE_ES_HkPacket_t_Dec(const char *inBuffer, uint32 inSize, CFE_ES_HkPacket_t *inOutObject);

uint32 CFE_ES_PerfStopCmd_t_Enc(const CFE_ES_PerfStopCmd_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 CFE_ES_PerfStopCmd_t_Dec(const char *inBuffer, uint32 inSize, CFE_ES_PerfStopCmd_t *inOutObject);

uint32 CFE_ES_WriteSyslogCmd_t_Enc(const CFE_ES_WriteSyslogCmd_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 CFE_ES_WriteSyslogCmd_t_Dec(const char *inBuffer, uint32 inSize, CFE_ES_WriteSyslogCmd_t *inOutObject);

uint32 CFE_ES_WriteERlogCmd_t_Enc(const CFE_ES_WriteERlogCmd_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 CFE_ES_WriteERlogCmd_t_Dec(const char *inBuffer, uint32 inSize, CFE_ES_WriteERlogCmd_t *inOutObject);

uint32 CFE_ES_QueryAllCmd_t_Enc(const CFE_ES_QueryAllCmd_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 CFE_ES_QueryAllCmd_t_Dec(const char *inBuffer, uint32 inSize, CFE_ES_QueryAllCmd_t *inOutObject);

uint32 CFE_ES_OneAppTlm_t_Enc(const CFE_ES_OneAppTlm_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 CFE_ES_OneAppTlm_t_Dec(const char *inBuffer, uint32 inSize, CFE_ES_OneAppTlm_t *inOutObject);

uint32 CFE_ES_ShellPacket_t_Enc(const CFE_ES_ShellPacket_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 CFE_ES_ShellPacket_t_Dec(const char *inBuffer, uint32 inSize, CFE_ES_ShellPacket_t *inOutObject);

uint32 CFE_ES_RestartCmd_t_Enc(const CFE_ES_RestartCmd_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 CFE_ES_RestartCmd_t_Dec(const char *inBuffer, uint32 inSize, CFE_ES_RestartCmd_t *inOutObject);

uint32 CFE_ES_OverWriteSysLogCmd_t_Enc(const CFE_ES_OverWriteSysLogCmd_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 CFE_ES_OverWriteSysLogCmd_t_Dec(const char *inBuffer, uint32 inSize, CFE_ES_OverWriteSysLogCmd_t *inOutObject);

uint32 CFE_ES_PerfSetFilterMaskCmd_t_Enc(const CFE_ES_PerfSetFilterMaskCmd_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 CFE_ES_PerfSetFilterMaskCmd_t_Dec(const char *inBuffer, uint32 inSize, CFE_ES_PerfSetFilterMaskCmd_t *inOutObject);

#ifdef __cplusplus
} /* extern "C" */
#endif
