/* This file was autogenerated from template version 0.0.0.1 and autogenerator version 0.0.0.1 */
#include "px4_msgs.h"
#include "pb.h"
#include "pb_encode.h"
#include "pb_decode.h"
#include "pb_lib.h"
#include "px4_position_setpoint_triplet.pb.h"

#ifdef __cplusplus
extern "C" {
#endif

uint32 PX4_PositionSetpointTripletMsg_t_Enc(const PX4_PositionSetpointTripletMsg_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 PX4_PositionSetpointTripletMsg_t_Dec(const char *inBuffer, uint32 inSize, PX4_PositionSetpointTripletMsg_t *inOutObject);

#ifdef __cplusplus
} /* extern "C" */
#endif
