# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ea_start.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ea_start.proto',
  package='',
  serialized_pb=_b('\n\x0e\x65\x61_start.proto\"2\n\x0b\x65\x61_start_pb\x12\x13\n\x0binterpreter\x18\x01 \x02(\t\x12\x0e\n\x06script\x18\x02 \x02(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_EA_START_PB = _descriptor.Descriptor(
  name='ea_start_pb',
  full_name='ea_start_pb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='interpreter', full_name='ea_start_pb.interpreter', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='script', full_name='ea_start_pb.script', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=68,
)

DESCRIPTOR.message_types_by_name['ea_start_pb'] = _EA_START_PB

ea_start_pb = _reflection.GeneratedProtocolMessageType('ea_start_pb', (_message.Message,), dict(
  DESCRIPTOR = _EA_START_PB,
  __module__ = 'ea_start_pb2'
  # @@protoc_insertion_point(class_scope:ea_start_pb)
  ))
_sym_db.RegisterMessage(ea_start_pb)


# @@protoc_insertion_point(module_scope)
